### ISSUE TITLE
Crash constantly

### ISSUE THREAD

**Issue by svlkent** [RonnyWinkler/homey.mqtthub#1]
Hello! My MQTT crashes constantly since a day ago
Cant find why. Have tried to uninstall and reinstall

Diagnostic: 1340100d-5007-458f-83be-b52163dcab0b

**Comment by RonnyWinkler** [comment]
Pelease add a send delay in app settings (20 or up to 50ms). In most cases, that distributes the load over a longer time prerventing CPU usage caused crashes.
