### ISSUE TITLE
 displayName not applied when importing configuration script

### ISSUE THREAD

**Issue by entotentrefirefemskjetten** [RonnyWinkler/homey.mqtthub#3]
When importing a configuration script, the displayName property is not applied correctly. It only works when set manually for the first time during setup. This appears to be a bug, as displayName should be recognized and applied consistently, whether added manually or through a script.

**Comment by RonnyWinkler** [comment]
Can you please show some screenshots what you want to import (HA developer tools details)?
And what means "set manually"?
Is "friendly_name" recognized instead?

**Comment by entotentrefirefemskjetten** [comment]
When I select "new device", press "MQTT Hub" then "MQTT device." Select Device Name, Class and Icon. I get to set "Capabilities" 
See screenshot.

It generates this code.
`{
  "measure_voltage": {
    "capability": "measure_voltage",
    "stateTopic": "AMS/meter/l1/voltage",
    "setTopic": "",
    "valueTemplate": "",
    "outputTemplate": "",
    "displayName": "My custom name"
  }
}`

If I try to set a new name, via the advanced settings, it just shows "Voltage"

Hope this clarify things.

![screenshot01](https://github.com/user-attachments/assets/7139e08b-dbd5-4382-8260-6e320b4d241d)
![screenshot02](https://github.com/user-attachments/assets/605495b1-1046-47f9-933c-677732ea455f)
![screenshot03](https://github.com/user-attachments/assets/4e06bdb7-96df-4f77-876d-59b7fdc85507)

**Comment by entotentrefirefemskjetten** [comment]
As far as I know, you only get to see the "Add cabability" menu when you add the device. 
And It's a slow process to add many capabilities to one device.
Thank you for your effort by the way :)

**Comment by RonnyWinkler** [comment]
Can you please copy the JSON after changing the capability title (changed displayName).
I tried a lot and displayName is updated correctly. Only if you remove it (or displayName is not found), the capability title is used instead.

**Comment by entotentrefirefemskjetten** [comment]
`{
  "measure_voltage": {
    "capability": "measure_voltage",
    "stateTopic": "AMS/meter/l1/voltage",
    "setTopic": "",
    "valueTemplate": "",
    "outputTemplate": "",
    "friendly_name": "My custom name 2"
  }
}`

Shows like this:
![screenshot03](https://github.com/user-attachments/assets/6d96ced4-588a-49a4-99a5-9c2cc684d9f2)

**Comment by entotentrefirefemskjetten** [comment]
Here is my Homey System Info:
Model
Homey Pro (Early 2023)
Version
12.2.0

**Comment by RonnyWinkler** [comment]
Strange...
`{
  "measure_power": {
    "capability": "measure_power",
    "stateTopic": "homie/homey-dev/homey-dev/measure-power",
    "setTopic": "",
    "valueTemplate": "",
    "outputTemplate": "",
    "displayName": "My Custom Name 2"
  }
}`

![grafik](https://github.com/user-attachments/assets/5e81e69b-bf0d-40ee-b8cc-96cde890e9fc)

It's working on HP19 and HP23.

**Comment by entotentrefirefemskjetten** [comment]
Why isn't it working on my homey :( 

Anything I need to install, java framework or something?

**Comment by RonnyWinkler** [comment]
Nothing is needed. 
I will update to 12.2.0 (was still on previous version) and try again...

**Comment by entotentrefirefemskjetten** [comment]
I do this to add device:  When I select "new device", press "MQTT Hub" then "MQTT device." 
![screenshot04](https://github.com/user-attachments/assets/1c9ca153-df33-45ed-aedc-30a6e567fee8)

**Comment by entotentrefirefemskjetten** [comment]
I uninstalled rebooted and reinstalled MQTT hub. And now everything seems to be working.
Sorry for the trouble.
